### ISSUE TITLE
uninitialized constant Celluloid::Logger

### ISSUE THREAD

**Issue by kostya** [celluloid/reel-rack#22]
celluloid 0.17.2
reel 0.5.0

require 'reel/rack/server'

```
uninitialized constant Celluloid::Logger
/Users/kostya/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-rack-0.2.2/lib/reel/rack/server.rb:9:in `<class:Server>'
/Users/kostya/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-rack-0.2.2/lib/reel/rack/server.rb:8:in `<module:Rack>'
/Users/kostya/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-rack-0.2.2/lib/reel/rack/server.rb:7:in `<module:Reel>'
/Users/kostya/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/reel-rack-0.2.2/lib/reel/rack/server.rb:6:in `<top (required)>'
```

**Comment by digitalextremist** [comment]
That symbol needs to be changed to `Celluloid::Internals::Logger` in the gem.

**Comment by jlyonsmith** [comment]
:+1:

**Comment by tmm1** [comment]
Hitting this issue as well.

**Comment by digitalextremist** [comment]
@pulkit4tech do you have a bit of time to update the constant to `Celluloid::Internals::Logger` and post a PR?

@tmm1 @jlyonsmith for now, you can do `Celluloid::Logger = Celluloid::Internals::Logger` and let us know if you run into anything else like that.

**Comment by pulkit4tech** [comment]
Sure @digitalextremist, Currently I am out of station, but will make a PR for it very soon :smiley:

**Comment by kostya** [comment]
can you release gem with this fix?
